on: [workflow_dispatch]

name: Strand Calendar

jobs:
  generate_calendar:
    name: Generate Calendar
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Setup
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      - run: npm ci

      # Generate files
      - id: date
        run: echo "{currentDate}={$(TZ=Europe/Belfast date +'%Y-%m-%d')}" >> $GITHUB_STATE
      - id: time
        run: echo "{currentTime}={$(TZ=Europe/Belfast date +'%H:%M:%S')}" >> $GITHUB_STATE
      - run: node index.js

      # Create release with assets
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: false
          artifactErrorsFailBuild: true
          artifacts: "strand-calendar.ics,strand-shows.json"
          makeLatest: true
          tag: ${{ steps.date.outputs.currentDate }}
          commit: main
          body: "Calendar and data files generated at ${{ steps.time.outputs.currentTime }} on ${{ steps.date.outputs.currentDate }}"
