on: [workflow_dispatch]

jobs:
  generate_calendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Setup
      - uses: actions/checkout@v3
      - id: date
        run: echo "::set-output name=date::$(TZ=Europe/Belfast date +'%Y-%m-%d')"
      - id: time
        run: echo "::set-output name=time::$(TZ=Europe/Belfast date +'%H:%M:%S')"
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      - run: npm ci

      # Generate files
      - run: node index.js

      # Create release with assets
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: false
          artifactErrorsFailBuild: true
          artifacts: "strand-calendar.ics,strand-shows.json"
          makeLatest: false
          tag: test-${{ steps.date.outputs.date }}
          commit: main
          body: "Calendar and data files generated at ${{ steps.date.outputs.time }} on ${{ steps.date.outputs.date }}"
